### ISSUE TITLE
Domain model 

### ISSUE THREAD

**Issue by manolisgiannakis** [vasMil/GymBuddy#11]

**Comment by vasMil** [comment]
Done: Create a somewhat abstract domain model with basic classes, attributes and methods.
Next task 1: Add new classes that will become evident during the development of the sequence diagrams.
Next task 2: Add UI classes.

**Comment by manolisgiannakis** [comment]
Για το use case "Entering Competition" θα πρέπει να προστεθεί ένα button "Cancel" στο 5ο mock-up screen που του αντιστοιχεί.
To ίδιο και για το 6ο mock-up
