### ISSUE TITLE
Mock-ups 

### ISSUE THREAD

**Issue by manolisgiannakis** [vasMil/GymBuddy#12]
Attempt to add 1 or 2 mockups for each use case. It is only an ehancement no need to rush things for this milestone!

**Comment by vasMil** [comment]
Moves Manolis Comment: Για το use case "Entering Competition" θα πρέπει να προστεθεί ένα button "Cancel" στο 5ο mock-up screen που του αντιστοιχεί.
To ίδιο και για το 6ο mock-up
