### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by manolisgiannakis** [vasMil/GymBuddy#13]
- Αρης να κανει εναλλακτικη ροή 
- Βασιλης να βαλει απο το διαχειριστη include ή extend (στο use case diagram)
- 3 καινουργια use case (να εχει το καθενα τουλαχιστον 9 βηματα)
- συννεφακια admin ειναι 2 ιδια

**Comment by manolisgiannakis** [comment]
Αντικαθιστουμε την "εγκριση βιντεο" με την "ευρεση γυμναστηριου"
Αντικαθιστουμε την "αποδοχη/αποριψη πιστοποιητικων απο αντμιν" με τη "δημιουργια προγραμματος"

**Comment by vasMil** [comment]
Ο Άρης έκανε την εναλλακτική ροή

**Comment by vasMil** [comment]
Να προστεθεί στο use case diagram το use case: Αναβάθμιση Αθλητή σε Γυμναστή
