### ISSUE TITLE
Sequence diagrams

### ISSUE THREAD

**Issue by manolisgiannakis** [vasMil/GymBuddy#14]
- Απο πεμπτη και μετα αφου θα ειναι ετοιμα τα usecases και robustness ΟΛΩΝ.

**Comment by vasMil** [comment]
Άλεξ -> Ανάρτηση Βίντεο, Εύρεση γυμναστηρίου (reviewer: Βασίλης)
Αλέξης -> Διαδικασία πιστοποίησης γυμναστή, Δημιουργία προγράμματος (reviewer: Άλεξ)
Βασίλης -> Αποδοχή αιτήματος συνεργασίας από γυμναστή,  Έλεγχος αναφοράς από διαχειριστή (reviewer: Άρης)
Άρης -> Εύρεση προγράμματος, Καταγραφή άσκησης, Έναρξη προπόνησης (reviewer: Μανόλης)
Μανόλης -> Εύρεση Γυμναστή, Είσοδος στην κατάταξη διαγωνισμού (reviewer: Αλέξης)
