### ISSUE TITLE
ProjectCode-v0.2

### ISSUE THREAD

**Issue by vasMil** [vasMil/GymBuddy#16]
Ο κάθε reviewer από τα sequence πρέπει να αναπτύξει κώδικα για τα διαγράμματα εκείνα που έκανε review.
Στόχος: 2 sequence από τον καθένα.

**Comment by alexkavoulas** [comment]
Αλεξ -> Διαδικασια πιστοποιησης γυμναστη , Δημιουργια Προγραμματος
Αλεξης -> Ευρεση γυμναστη, Εισοδος στην καταταξη διαγωνισμου
Αρης -> Αποδοχη αιτηματος συνεργασιας απο γυμναστη, Ελεγγχος αναφορας απο διαχειριστη
Μανολης -> Ευρεση προγραμματος, Καταγραφη ασκησης, Εναρξη προπονησης
Βασιλης -> Αναρτηση βιντεο, Ευρεση γυμναστηριου
